// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	BlockGuy4 = 0,
	BlockGuy2 = 1,
	BlockGuy3 = 2,
	BlockGuy1 = 3,
	BlockGuy7 = 4,
	BlockGuy8 = 5,
}
